export const identityAbi = [
  {
    type: 'function',
    name: 'aiMintFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancelPaymentRequest',
    inputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimNFTRewards',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collectStakingRewards',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createPaymentRequest',
    inputs: [
      { name: 'payerHandle', type: 'string', internalType: 'string' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'dueAt', type: 'uint64', internalType: 'uint64' },
      { name: 'memo', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'effectivePaymentRequestStatus',
    inputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'uint8', internalType: 'enum Series9Identity.PaymentRequestStatus' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'handleOf',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'legacyHandleReservationCursor',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'legacyHandleReservationsFinalized',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'legacyHandlePriorityDeadline',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'humanMintFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isAI',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mintIdentity',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'bio', type: 'string', internalType: 'string' },
      { name: 'entityType', type: 'uint8', internalType: 'enum Series9Identity.EntityType' },
      { name: 'hue', type: 'uint8', internalType: 'uint8' },
      { name: 'saturation', type: 'uint8', internalType: 'uint8' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'mintIdentityWithHandle',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'bio', type: 'string', internalType: 'string' },
      { name: 'entityType', type: 'uint8', internalType: 'enum Series9Identity.EntityType' },
      { name: 'hue', type: 'uint8', internalType: 'uint8' },
      { name: 'saturation', type: 'uint8', internalType: 'uint8' },
      { name: 'handle', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nameOf',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOfHandle',
    inputs: [{ name: 'handle', type: 'string', internalType: 'string' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerTokenId',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payPaymentRequest',
    inputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'paymentId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'payPaymentRequestWithSig',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
      { name: 'deadline', type: 'uint256', internalType: 'uint256' },
      { name: 'signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: 'paymentId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'paymentNonces',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payPaymentRequestDigest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
      { name: 'deadline', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payToHandle',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'recipientHandle', type: 'string', internalType: 'string' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'memo', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: 'paymentId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'payeePaymentRequestCount',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payeePaymentRequestIdAt',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payerPaymentRequestCount',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payerPaymentRequestIdAt',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paymentRequest',
    inputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'payerTokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'payeeTokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'dueAt', type: 'uint64', internalType: 'uint64' },
      { name: 'status', type: 'uint8', internalType: 'enum Series9Identity.PaymentRequestStatus' },
      { name: 'memo', type: 'string', internalType: 'string' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingNFTRewards',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingStakingRewards',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'reputationScoreOf',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'seedLegacyHandleReservations',
    inputs: [{ name: 'maxTokens', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setHandle',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'handle', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenIdOfHandle',
    inputs: [{ name: 'handle', type: 'string', internalType: 'string' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'avatarConfig',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'skinTone', type: 'uint8', internalType: 'uint8' },
      { name: 'hairStyle', type: 'uint8', internalType: 'uint8' },
      { name: 'hairColor', type: 'uint8', internalType: 'uint8' },
      { name: 'eyes', type: 'uint8', internalType: 'uint8' },
      { name: 'mouth', type: 'uint8', internalType: 'uint8' },
      { name: 'outfit', type: 'uint8', internalType: 'uint8' },
      { name: 'accessory', type: 'uint8', internalType: 'uint8' },
      { name: 'background', type: 'uint8', internalType: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setAvatar',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'config',
        type: 'tuple',
        internalType: 'struct Series9IdentityRenderer.AvatarConfig',
        components: [
          { name: 'skinTone', type: 'uint8', internalType: 'uint8' },
          { name: 'hairStyle', type: 'uint8', internalType: 'uint8' },
          { name: 'hairColor', type: 'uint8', internalType: 'uint8' },
          { name: 'eyes', type: 'uint8', internalType: 'uint8' },
          { name: 'mouth', type: 'uint8', internalType: 'uint8' },
          { name: 'outfit', type: 'uint8', internalType: 'uint8' },
          { name: 'accessory', type: 'uint8', internalType: 'uint8' },
          { name: 'background', type: 'uint8', internalType: 'uint8' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AvatarUpdated',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      {
        name: 'config',
        type: 'tuple',
        indexed: false,
        internalType: 'struct Series9IdentityRenderer.AvatarConfig',
        components: [
          { name: 'skinTone', type: 'uint8', internalType: 'uint8' },
          { name: 'hairStyle', type: 'uint8', internalType: 'uint8' },
          { name: 'hairColor', type: 'uint8', internalType: 'uint8' },
          { name: 'eyes', type: 'uint8', internalType: 'uint8' },
          { name: 'mouth', type: 'uint8', internalType: 'uint8' },
          { name: 'outfit', type: 'uint8', internalType: 'uint8' },
          { name: 'accessory', type: 'uint8', internalType: 'uint8' },
          { name: 'background', type: 'uint8', internalType: 'uint8' },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'walletImplementation',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'walletOf',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'predictWalletAddress',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createWallet',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'wallet', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
] as const;
