export const stakingAbi = [
  {"type": "constructor","inputs": [],"stateMutability": "nonpayable"},
  {"type": "receive","stateMutability": "payable"},
  {"type": "function","name": "UPGRADE_INTERFACE_VERSION","inputs": [],"outputs": [{"name": "","type": "string","internalType": "string"}],"stateMutability": "view"},
  {"type": "function","name": "accruedCreationFees","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "cachedMonadDelegatedShareBps","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "cachedMonadObservedApy","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "cachedValidatorScore","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "claimRewards","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "claimUnstaked","inputs": [{"name": "requestId","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "claimUnstakedMonad","inputs": [{"name": "requestId","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "earned","inputs": [{"name": "account","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "feePendingRewards","inputs": [{"name": "","type": "address","internalType": "address"},{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "feeRewardDebt","inputs": [{"name": "","type": "address","internalType": "address"},{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "forceReleaseUndelegateTicket","inputs": [{"name": "ticketIndex","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "harvestMonadValidatorRewards","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "hasCachedValidatorScore","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "initialize","inputs": [{"name": "ser9Token","type": "address","internalType": "address"},{"name": "rewardPerBlock","type": "uint256","internalType": "uint256"},{"name": "initialOwner","type": "address","internalType": "address"},{"name": "managedTokenImplementation_","type": "address","internalType": "address"},{"name": "initialCreationFee","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "initializeV2","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "initializeV3","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "isTrackedValidator","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "lastUpdateBlock","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "managedTokenImplementation","inputs": [],"outputs": [{"name": "","type": "address","internalType": "address"}],"stateMutability": "view"},
  {"type": "function","name": "maxMintable","inputs": [{"name": "user","type": "address","internalType": "address"},{"name": "token","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadCoverageRequestCursor","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadEarned","inputs": [{"name": "account","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadFallbackValidatorCursor","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadHarvestValidatorCursor","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadLastUpdateBlock","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadPendingUndelegateCursor","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadRebalanceKeepers","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "monadRebalanceValidatorCursor","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadRewardPerToken","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadRewardPerTokenStored","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadRewardRatePerBlock","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadRewards","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadSlashingDeficit","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadStakedBalance","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadUndelegateValidatorCursor","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "monadUnstakeDelayEpochs","inputs": [],"outputs": [{"name": "","type": "uint64","internalType": "uint64"}],"stateMutability": "view"},
  {"type": "function","name": "monadUnstakeRequest","inputs": [{"name": "user","type": "address","internalType": "address"},{"name": "requestId","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "amount","type": "uint256","internalType": "uint256"},{"name": "requestEpoch","type": "uint64","internalType": "uint64"},{"name": "minClaimEpoch","type": "uint64","internalType": "uint64"},{"name": "claimed","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "monadUnstakeRequestCount","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "nextWithdrawIdByValidator","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "","type": "uint8","internalType": "uint8"}],"stateMutability": "view"},
  {"type": "function","name": "owner","inputs": [],"outputs": [{"name": "","type": "address","internalType": "address"}],"stateMutability": "view"},
  {"type": "function","name": "pause","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "paused","inputs": [],"outputs": [{"name": "","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "pendingMonadUnstakePrincipal","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "pendingUndelegateTickets","inputs": [{"name": "","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "validatorId","type": "uint64","internalType": "uint64"},{"name": "withdrawId","type": "uint8","internalType": "uint8"},{"name": "amount","type": "uint256","internalType": "uint256"},{"name": "claimableEpoch","type": "uint64","internalType": "uint64"},{"name": "withdrawn","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "permit2","inputs": [],"outputs": [{"name": "","type": "address","internalType": "contract IPermit2"}],"stateMutability": "view"},
  {"type": "function","name": "processMaturedMonadUndelegations","inputs": [{"name": "maxTickets","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "processed","type": "uint256","internalType": "uint256"}],"stateMutability": "nonpayable"},
  {"type": "function","name": "processPendingMonadUnstakeCoverage","inputs": [{"name": "maxValidators","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "maxClaimEpoch","type": "uint64","internalType": "uint64"}],"stateMutability": "nonpayable"},
  {"type": "function","name": "protocolMonadYieldAccrued","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "proxiableUUID","inputs": [],"outputs": [{"name": "","type": "bytes32","internalType": "bytes32"}],"stateMutability": "view"},
  {"type": "function","name": "rebalanceMonadDelegations","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "renounceOwnership","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "requestManagedTokenUpgrade","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "requestUnstakeMonad","inputs": [{"name": "amount","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "requestId","type": "uint256","internalType": "uint256"}],"stateMutability": "nonpayable"},
  {"type": "function","name": "rewardPerToken","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "rewardPerTokenStored","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "rewardRatePerBlock","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "rewardWeightBalance","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "rewards","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "ser9","inputs": [],"outputs": [{"name": "","type": "address","internalType": "contract SER9Token"}],"stateMutability": "view"},
  {"type": "function","name": "ser9UnstakeRequest","inputs": [{"name": "user","type": "address","internalType": "address"},{"name": "requestId","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "amount","type": "uint256","internalType": "uint256"},{"name": "requestEpoch","type": "uint64","internalType": "uint64"},{"name": "minClaimEpoch","type": "uint64","internalType": "uint64"},{"name": "claimed","type": "bool","internalType": "bool"}],"stateMutability": "view"},
  {"type": "function","name": "ser9UnstakeRequestCount","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "setMonadRebalanceKeeper","inputs": [{"name": "keeper","type": "address","internalType": "address"},{"name": "allowed","type": "bool","internalType": "bool"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "setMonadRewardRatePerBlock","inputs": [{"name": "newRate","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "setMonadUnstakeDelayEpochs","inputs": [{"name": "newDelayEpochs","type": "uint64","internalType": "uint64"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "setPermit2","inputs": [{"name": "newPermit2","type": "address","internalType": "address"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "setRewardRatePerBlock","inputs": [{"name": "newRewardRatePerBlock","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "setSer9StakingContract","inputs": [{"name": "newStakingContract","type": "address","internalType": "address"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "setTokenCreationFee","inputs": [{"name": "newFee","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "stake","inputs": [{"name": "amount","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "stakeMonad","inputs": [],"outputs": [],"stateMutability": "payable"},
  {"type": "function","name": "stakeWithPermit2","inputs": [{"name": "amount","type": "uint256","internalType": "uint256"},{"name": "permitSingle","type": "tuple","internalType": "struct IPermit2.PermitSingle","components": [{"name": "details","type": "tuple","internalType": "struct IPermit2.PermitDetails","components": [{"name": "token","type": "address","internalType": "address"},{"name": "amount","type": "uint160","internalType": "uint160"},{"name": "expiration","type": "uint48","internalType": "uint48"},{"name": "nonce","type": "uint48","internalType": "uint48"}]},{"name": "spender","type": "address","internalType": "address"},{"name": "sigDeadline","type": "uint256","internalType": "uint256"}]},{"name": "permitSignature","type": "bytes","internalType": "bytes"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "stakedBalance","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "sweepCreationFees","inputs": [{"name": "to","type": "address","internalType": "address"},{"name": "amount","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "targetValidatorCount","inputs": [],"outputs": [{"name": "","type": "uint8","internalType": "uint8"}],"stateMutability": "view"},
  {"type": "function","name": "targetValidatorIds","inputs": [{"name": "","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "","type": "uint64","internalType": "uint64"}],"stateMutability": "view"},
  {"type": "function","name": "targetValidatorWeightsBps","inputs": [{"name": "","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "","type": "uint16","internalType": "uint16"}],"stateMutability": "view"},
  {"type": "function","name": "tokenCreationFee","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "totalDelegatedMonad","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "totalMonadStaked","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "totalPendingMonadUnstakeUncovered","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "totalPendingUndelegateMonad","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "totalStaked","inputs": [],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "trackedValidators","inputs": [{"name": "","type": "uint256","internalType": "uint256"}],"outputs": [{"name": "","type": "uint64","internalType": "uint64"}],"stateMutability": "view"},
  {"type": "function","name": "transferAllExcessMonadYield","inputs": [{"name": "recipient","type": "address","internalType": "address payable"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "transferExcessMonadYield","inputs": [{"name": "recipient","type": "address","internalType": "address payable"},{"name": "amount","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "transferOwnership","inputs": [{"name": "newOwner","type": "address","internalType": "address"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "unlockedStake","inputs": [{"name": "user","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "unpause","inputs": [],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "unstake","inputs": [{"name": "amount","type": "uint256","internalType": "uint256"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "upgradeManagedToken","inputs": [{"name": "token","type": "address","internalType": "address"},{"name": "data","type": "bytes","internalType": "bytes"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "upgradeSer9","inputs": [{"name": "newSer9Impl","type": "address","internalType": "address"},{"name": "ser9Data","type": "bytes","internalType": "bytes"}],"outputs": [],"stateMutability": "nonpayable"},
  {"type": "function","name": "upgradeToAndCall","inputs": [{"name": "newImplementation","type": "address","internalType": "address"},{"name": "data","type": "bytes","internalType": "bytes"}],"outputs": [],"stateMutability": "payable"},
  {"type": "function","name": "userMonadRewardPerTokenPaid","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "userRewardPerTokenPaid","inputs": [{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "userTokenCollateralUsed","inputs": [{"name": "","type": "address","internalType": "address"},{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "userTokenDebt","inputs": [{"name": "","type": "address","internalType": "address"},{"name": "","type": "address","internalType": "address"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "validatorDelegatedAmount","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "validatorPendingUndelegateAmount","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "function","name": "validatorSamples","inputs": [{"name": "","type": "uint64","internalType": "uint64"}],"outputs": [{"name": "accRewardPerToken","type": "uint256","internalType": "uint256"},{"name": "sampledBlock","type": "uint256","internalType": "uint256"},{"name": "commission","type": "uint256","internalType": "uint256"}],"stateMutability": "view"},
  {"type": "event","name": "CreationFeesSwept","inputs": [{"name": "to","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "FeeRewardsClaimed","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "rewardAmount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "FeeTokenStaked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "userStakeAfter","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "FeeTokenUnstaked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "userStakeAfter","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "Initialized","inputs": [{"name": "version","type": "uint64","indexed": false,"internalType": "uint64"}],"anonymous": false},
  {"type": "event","name": "Locked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "totalLocked","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "ManagedTokenBurnedAndUnlocked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "burnAmount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "unlockedAmount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "usedLockedAfter","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "lockedAfter","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "ManagedTokenCreated","inputs": [{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "creator","type": "address","indexed": true,"internalType": "address"},{"name": "mintRate","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "feeEnabled","type": "bool","indexed": false,"internalType": "bool"},{"name": "feeBps","type": "uint16","indexed": false,"internalType": "uint16"},{"name": "name","type": "string","indexed": false,"internalType": "string"},{"name": "symbol","type": "string","indexed": false,"internalType": "string"}],"anonymous": false},
  {"type": "event","name": "ManagedTokenImplementationUpdated","inputs": [{"name": "previousImpl","type": "address","indexed": false,"internalType": "address"},{"name": "newImpl","type": "address","indexed": false,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "ManagedTokenMinted","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "collateralCost","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "usedLockedAfter","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "ManagedTokenUpgraded","inputs": [{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "newImplementation","type": "address","indexed": true,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "MonadClaimRewardsFailed","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "reason","type": "bytes","indexed": false,"internalType": "bytes"}],"anonymous": false},
  {"type": "event","name": "MonadDelegateFailed","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "reason","type": "bytes","indexed": false,"internalType": "bytes"}],"anonymous": false},
  {"type": "event","name": "MonadRebalanceKeeperUpdated","inputs": [{"name": "keeper","type": "address","indexed": true,"internalType": "address"},{"name": "allowed","type": "bool","indexed": false,"internalType": "bool"}],"anonymous": false},
  {"type": "event","name": "MonadRebalanced","inputs": [{"name": "totalMonadStaked","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "totalDelegatedMonad","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "totalPendingUndelegateMonad","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadRewardRateUpdated","inputs": [{"name": "previousRate","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "newRate","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadStaked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadTargetsUpdated","inputs": [{"name": "validatorIds","type": "uint64[5]","indexed": false,"internalType": "uint64[5]"},{"name": "weightsBps","type": "uint16[5]","indexed": false,"internalType": "uint16[5]"},{"name": "targetCount","type": "uint8","indexed": false,"internalType": "uint8"}],"anonymous": false},
  {"type": "event","name": "MonadUndelegateQueued","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "withdrawId","type": "uint8","indexed": true,"internalType": "uint8"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "claimableEpoch","type": "uint64","indexed": false,"internalType": "uint64"}],"anonymous": false},
  {"type": "event","name": "MonadUndelegateTicketForceReleased","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "withdrawId","type": "uint8","indexed": true,"internalType": "uint8"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadUnstakeClaimed","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "requestId","type": "uint256","indexed": true,"internalType": "uint256"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadUnstakeDelayEpochsUpdated","inputs": [{"name": "previousEpochs","type": "uint64","indexed": false,"internalType": "uint64"},{"name": "newEpochs","type": "uint64","indexed": false,"internalType": "uint64"}],"anonymous": false},
  {"type": "event","name": "MonadUnstakeRequested","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "requestId","type": "uint256","indexed": true,"internalType": "uint256"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "requestEpoch","type": "uint64","indexed": false,"internalType": "uint64"},{"name": "minClaimEpoch","type": "uint64","indexed": false,"internalType": "uint64"}],"anonymous": false},
  {"type": "event","name": "MonadWithdrawProcessed","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "withdrawId","type": "uint8","indexed": true,"internalType": "uint8"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadWithdrawShortfall","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "withdrawId","type": "uint8","indexed": true,"internalType": "uint8"},{"name": "expected","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "received","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "shortfall","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadYieldAccrued","inputs": [{"name": "validatorId","type": "uint64","indexed": true,"internalType": "uint64"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "MonadYieldTransferred","inputs": [{"name": "recipient","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "OwnershipTransferred","inputs": [{"name": "previousOwner","type": "address","indexed": true,"internalType": "address"},{"name": "newOwner","type": "address","indexed": true,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "Paused","inputs": [{"name": "account","type": "address","indexed": false,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "Permit2Updated","inputs": [{"name": "previousPermit2","type": "address","indexed": true,"internalType": "address"},{"name": "newPermit2","type": "address","indexed": true,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "RewardClaimed","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "rewardAmount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "RewardRateUpdated","inputs": [{"name": "newRewardRatePerBlock","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "Ser9UnstakeClaimed","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "requestId","type": "uint256","indexed": true,"internalType": "uint256"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "Ser9UnstakeRequested","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "requestId","type": "uint256","indexed": true,"internalType": "uint256"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "requestEpoch","type": "uint64","indexed": false,"internalType": "uint64"},{"name": "minClaimEpoch","type": "uint64","indexed": false,"internalType": "uint64"}],"anonymous": false},
  {"type": "event","name": "Ser9Upgraded","inputs": [{"name": "ser9Proxy","type": "address","indexed": true,"internalType": "address"},{"name": "newImplementation","type": "address","indexed": true,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "Staked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "TokenCreationFeeUpdated","inputs": [{"name": "previousFee","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "newFee","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "TokenFeeBpsUpdated","inputs": [{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "feeBps","type": "uint16","indexed": false,"internalType": "uint16"}],"anonymous": false},
  {"type": "event","name": "TokenFeeExemptUpdated","inputs": [{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "account","type": "address","indexed": true,"internalType": "address"},{"name": "isExempt","type": "bool","indexed": false,"internalType": "bool"}],"anonymous": false},
  {"type": "event","name": "TokenMintPolicyConfigured","inputs": [{"name": "token","type": "address","indexed": true,"internalType": "address"},{"name": "maxSupply","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "maxMultiplierBps","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "rampStartBps","type": "uint16","indexed": false,"internalType": "uint16"}],"anonymous": false},
  {"type": "event","name": "Unpaused","inputs": [{"name": "account","type": "address","indexed": false,"internalType": "address"}],"anonymous": false},
  {"type": "event","name": "Unstaked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "UnusedLockedUnlocked","inputs": [{"name": "user","type": "address","indexed": true,"internalType": "address"},{"name": "amount","type": "uint256","indexed": false,"internalType": "uint256"},{"name": "lockedAfter","type": "uint256","indexed": false,"internalType": "uint256"}],"anonymous": false},
  {"type": "event","name": "Upgraded","inputs": [{"name": "implementation","type": "address","indexed": true,"internalType": "address"}],"anonymous": false},
  {"type": "error","name": "AddressEmptyCode","inputs": [{"name": "target","type": "address","internalType": "address"}]},
  {"type": "error","name": "CannotDisableStakingExemption","inputs": []},
  {"type": "error","name": "ERC1967InvalidImplementation","inputs": [{"name": "implementation","type": "address","internalType": "address"}]},
  {"type": "error","name": "ERC1967NonPayable","inputs": []},
  {"type": "error","name": "EnforcedPause","inputs": []},
  {"type": "error","name": "ExceedsMaxSupply","inputs": [{"name": "requestedSupply","type": "uint256","internalType": "uint256"},{"name": "maxSupply","type": "uint256","internalType": "uint256"}]},
  {"type": "error","name": "ExceedsMintLimit","inputs": []},
  {"type": "error","name": "ExpectedPause","inputs": []},
  {"type": "error","name": "FailedCall","inputs": []},
  {"type": "error","name": "FeeDisabled","inputs": []},
  {"type": "error","name": "ImplementationNotUUPSCompatible","inputs": [{"name": "implementation","type": "address","internalType": "address"}]},
  {"type": "error","name": "InsufficientCreationFee","inputs": []},
  {"type": "error","name": "InsufficientCreationFees","inputs": [{"name": "requested","type": "uint256","internalType": "uint256"},{"name": "available","type": "uint256","internalType": "uint256"}]},
  {"type": "error","name": "InsufficientLiquidMonad","inputs": [{"name": "requiredAmount","type": "uint256","internalType": "uint256"},{"name": "availableAmount","type": "uint256","internalType": "uint256"}]},
  {"type": "error","name": "InsufficientLockedBalance","inputs": []},
  {"type": "error","name": "InsufficientMonadStakedBalance","inputs": []},
  {"type": "error","name": "InsufficientStakedBalance","inputs": []},
  {"type": "error","name": "InsufficientTokenDebt","inputs": []},
  {"type": "error","name": "InsufficientUnlockedBalance","inputs": []},
  {"type": "error","name": "InsufficientUnusedLockedBalance","inputs": []},
  {"type": "error","name": "InvalidFeeConfiguration","inputs": []},
  {"type": "error","name": "InvalidFeeRecipientTarget","inputs": []},
  {"type": "error","name": "InvalidImplementation","inputs": [{"name": "implementation","type": "address","internalType": "address"}]},
  {"type": "error","name": "InvalidInitialization","inputs": []},
  {"type": "error","name": "InvalidManagedToken","inputs": []},
  {"type": "error","name": "InvalidMaxMultiplierBps","inputs": [{"name": "maxMultiplierBps","type": "uint256","internalType": "uint256"}]},
  {"type": "error","name": "InvalidPermit2Address","inputs": []},
  {"type": "error","name": "InvalidPermit2Spender","inputs": [{"name": "expectedSpender","type": "address","internalType": "address"},{"name": "permitSpender","type": "address","internalType": "address"}]},
  {"type": "error","name": "InvalidPermit2Token","inputs": [{"name": "expectedToken","type": "address","internalType": "address"},{"name": "permitToken","type": "address","internalType": "address"}]},
  {"type": "error","name": "InvalidRampStartBps","inputs": [{"name": "rampStartBps","type": "uint16","internalType": "uint16"}]},
  {"type": "error","name": "InvalidSweepRecipient","inputs": []},
  {"type": "error","name": "InvalidTokenAddress","inputs": []},
  {"type": "error","name": "InvalidUndelegateTicket","inputs": []},
  {"type": "error","name": "InvalidUnstakeDelayEpochs","inputs": []},
  {"type": "error","name": "InvalidUnstakeRequest","inputs": []},
  {"type": "error","name": "ManualLockDisabled","inputs": []},
  {"type": "error","name": "MintRateZero","inputs": []},
  {"type": "error","name": "MonadEpochReadFailed","inputs": []},
  {"type": "error","name": "MonadPayoutFailed","inputs": []},
  {"type": "error","name": "NoFeeRewards","inputs": []},
  {"type": "error","name": "NoRewards","inputs": []},
  {"type": "error","name": "NotInitialized","inputs": []},
  {"type": "error","name": "NotInitializing","inputs": []},
  {"type": "error","name": "OwnableInvalidOwner","inputs": [{"name": "owner","type": "address","internalType": "address"}]},
  {"type": "error","name": "OwnableUnauthorizedAccount","inputs": [{"name": "account","type": "address","internalType": "address"}]},
  {"type": "error","name": "Permit2AmountTooLow","inputs": [{"name": "requiredAmount","type": "uint256","internalType": "uint256"},{"name": "permitAmount","type": "uint256","internalType": "uint256"}]},
  {"type": "error","name": "Permit2NotConfigured","inputs": []},
  {"type": "error","name": "ReentrancyGuardReentrantCall","inputs": []},
  {"type": "error","name": "SafeCastOverflowedUintDowncast","inputs": [{"name": "bits","type": "uint8","internalType": "uint8"},{"name": "value","type": "uint256","internalType": "uint256"}]},
  {"type": "error","name": "SafeERC20FailedOperation","inputs": [{"name": "token","type": "address","internalType": "address"}]},
  {"type": "error","name": "UUPSUnauthorizedCallContext","inputs": []},
  {"type": "error","name": "UUPSUnsupportedProxiableUUID","inputs": [{"name": "slot","type": "bytes32","internalType": "bytes32"}]},
  {"type": "error","name": "UnauthorizedRebalanceOperator","inputs": []},
  {"type": "error","name": "UnauthorizedTokenCreator","inputs": []},
  {"type": "error","name": "UnauthorizedTokenOwner","inputs": [{"name": "token","type": "address","internalType": "address"},{"name": "ownerAddress","type": "address","internalType": "address"}]},
  {"type": "error","name": "UnstakeRequestAlreadyClaimed","inputs": []},
  {"type": "error","name": "UnstakeRequestNotClaimable","inputs": [{"name": "currentEpoch","type": "uint64","internalType": "uint64"},{"name": "minClaimEpoch","type": "uint64","internalType": "uint64"}]},
  {"type": "error","name": "UnsupportedProxiableUUID","inputs": [{"name": "implementation","type": "address","internalType": "address"},{"name": "uuid","type": "bytes32","internalType": "bytes32"}]},
  {"type": "error","name": "ZeroAmount","inputs": []}
] as const;